let OctokitClass = null;

async function getOctokitClass() {
  if (OctokitClass) return OctokitClass;
  const mod = await import('octokit');
  OctokitClass = mod.Octokit;
  return OctokitClass;
}

function normalizeFilePayload(input) {
  const parsed = typeof input === 'string' ? JSON.parse(input) : input;
  const root = parsed?.files && typeof parsed.files === 'object' ? parsed.files : parsed;

  const normalized = {};

  const pushEntry = (filePath, content) => {
    if (!filePath || typeof filePath !== 'string') return;

    const safePath = filePath
      .replace(/\\/g, '/')
      .replace(/^\/+/, '')
      .replace(/^\.\//, '')
      .trim();

    if (!safePath || safePath.includes('..') || safePath.endsWith('/')) return;

    normalized[safePath] =
      typeof content === 'string' ? content : JSON.stringify(content ?? '', null, 2);
  };

  const flatten = (value, prefix = '') => {
    if (!value) return;

    if (Array.isArray(value)) {
      for (const item of value) {
        if (item && typeof item === 'object' && typeof item.path === 'string') {
          pushEntry(item.path, item.content ?? item.data ?? '');
        }
      }
      return;
    }

    if (typeof value !== 'object') return;

    for (const [key, child] of Object.entries(value)) {
      if (!key) continue;

      if (typeof child === 'string') {
        const maybePath = prefix ? `${prefix}/${key}` : key;
        pushEntry(maybePath, child);
        continue;
      }

      if (child && typeof child === 'object') {
        if (typeof child.path === 'string' && (typeof child.content === 'string' || typeof child.data === 'string')) {
          pushEntry(child.path, child.content ?? child.data ?? '');
          continue;
        }

        const nextPrefix = prefix ? `${prefix}/${key}` : key;
        flatten(child, nextPrefix);
      }
    }
  };

  if (Array.isArray(root)) {
    flatten(root);
  } else if (root && typeof root === 'object') {
    for (const [key, value] of Object.entries(root)) {
      if (typeof value === 'string') {
        pushEntry(key, value);
      } else if (value && typeof value === 'object') {
        if (typeof value.path === 'string' && (typeof value.content === 'string' || typeof value.data === 'string')) {
          pushEntry(value.path, value.content ?? value.data ?? '');
        } else {
          flatten(value, key.includes('/') ? '' : key);
        }
      }
    }
  }

  return normalized;
}

const createAndPushRepo = async (githubToken, repoName, files, isPrivate = false) => {
  const Octokit = await getOctokitClass();
  const octokit = new Octokit({ auth: githubToken });

  const sanitizedName = repoName
    .toLowerCase()
    .replace(/[^a-z0-9-]/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '');

  const { data: repo } = await octokit.rest.repos.createForAuthenticatedUser({
    name: sanitizedName,
    private: isPrivate,
    auto_init: true,
    description: `Generated by Genesis.ai`,
  });

  const owner = repo.owner.login;
  const repoNameFinal = repo.name;
  const defaultBranch = repo.default_branch || 'main';

  const { data: ref } = await octokit.rest.git.getRef({
    owner,
    repo: repoNameFinal,
    ref: `heads/${defaultBranch}`,
  });

  const baseTreeSha = ref.object.sha;

  const { data: baseCommit } = await octokit.rest.git.getCommit({
    owner,
    repo: repoNameFinal,
    commit_sha: baseTreeSha,
  });

  const treeItems = [];
  const parsedFiles = normalizeFilePayload(files);

  for (const [filePath, content] of Object.entries(parsedFiles)) {
    const { data: blob } = await octokit.rest.git.createBlob({
      owner,
      repo: repoNameFinal,
      content: typeof content === 'string' ? content : JSON.stringify(content, null, 2),
      encoding: 'utf-8',
    });

    treeItems.push({
      path: filePath,
      mode: '100644',
      type: 'blob',
      sha: blob.sha,
    });
  }

  if (treeItems.length === 0) {
    throw new Error('No files were found to push to GitHub.');
  }

  const { data: tree } = await octokit.rest.git.createTree({
    owner,
    repo: repoNameFinal,
    base_tree: baseCommit.tree.sha,
    tree: treeItems,
  });

  const { data: newCommit } = await octokit.rest.git.createCommit({
    owner,
    repo: repoNameFinal,
    message: 'Initial project - Generated by Genesis.ai',
    tree: tree.sha,
    parents: [baseTreeSha],
  });

  await octokit.rest.git.updateRef({
    owner,
    repo: repoNameFinal,
    ref: `heads/${defaultBranch}`,
    sha: newCommit.sha,
  });

  return repo.html_url;
};

export default {
  createAndPushRepo,
};
