let OctokitClass = null;

async function getOctokitClass() {
  if (OctokitClass) return OctokitClass;
  const mod = await import('octokit');
  OctokitClass = mod.Octokit;
  return OctokitClass;
}

const createAndPushRepo = async (githubToken, repoName, files, isPrivate = false) => {
  const Octokit = await getOctokitClass();
  const octokit = new Octokit({ auth: githubToken });

  const sanitizedName = repoName
    .toLowerCase()
    .replace(/[^a-z0-9-]/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '');

  const { data: repo } = await octokit.rest.repos.createForAuthenticatedUser({
    name: sanitizedName,
    private: isPrivate,
    auto_init: true,
    description: `Generated by Genesis.ai`,
  });

  const owner = repo.owner.login;
  const repoNameFinal = repo.name;

  const { data: ref } = await octokit.rest.git.getRef({
    owner,
    repo: repoNameFinal,
    ref: 'heads/main',
  });

  const baseTreeSha = ref.object.sha;

  const { data: baseCommit } = await octokit.rest.git.getCommit({
    owner,
    repo: repoNameFinal,
    commit_sha: baseTreeSha,
  });

  const treeItems = [];
  const parsedFiles = typeof files === 'string' ? JSON.parse(files) : files;

  for (const [filePath, content] of Object.entries(parsedFiles)) {
    const { data: blob } = await octokit.rest.git.createBlob({
      owner,
      repo: repoNameFinal,
      content: typeof content === 'string' ? content : JSON.stringify(content, null, 2),
      encoding: 'utf-8',
    });

    treeItems.push({
      path: filePath,
      mode: '100644',
      type: 'blob',
      sha: blob.sha,
    });
  }

  const { data: tree } = await octokit.rest.git.createTree({
    owner,
    repo: repoNameFinal,
    base_tree: baseCommit.tree.sha,
    tree: treeItems,
  });

  const { data: newCommit } = await octokit.rest.git.createCommit({
    owner,
    repo: repoNameFinal,
    message: 'Initial project - Generated by Genesis.ai',
    tree: tree.sha,
    parents: [baseTreeSha],
  });

  await octokit.rest.git.updateRef({
    owner,
    repo: repoNameFinal,
    ref: 'heads/main',
    sha: newCommit.sha,
  });

  return repo.html_url;
};

export default {
  createAndPushRepo,
};
